### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by lifecreater** [nsumner/clang-plugins-demo#1]
Hello, thank you for your code. But when I do as what you said, I got error， I don't know why.
This is the log.
➜  build cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=True -DLLVM_DIR=~/code/llvm_xcode/lib/cmake/llvm  ..
-- Found LLVM 10.0.0svn
-- Using LLVMConfig.cmake in: ~/code/llvm_xcode/lib/cmake/llvm
-- Linker detection: ld64
LLVM STATUS:
  Definitions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
  Includes    /Users/wangao/code/llvm-project/llvm/include;/Users/wangao/code/llvm_xcode/include
              STATIC_INCLUDES-NOTFOUND;/Users/wangao/code/llvm_xcode/tools/clang/include
  Libraries   /Users/wangao/code/llvm_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/lib
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
STATIC_INCLUDES
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/lib
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/lib/function-printer
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/lib/function-printer
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/lib/function-printer
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/lib/streamchecker
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/lib/streamchecker
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/tools
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/tools/print-functions
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/tools/print-functions
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/tools/runstreamchecker
   used as include directory in directory /Users/wangao/Desktop/clang-plugins-demo-master/tools/runstreamchecker

-- Configuring incomplete, errors occurred!
See also "/Users/wangao/Desktop/clang-plugins-demo-master/build/CMakeFiles/CMakeOutput.log".

**Comment by nsumner** [comment]
The plugin infrastructure for clang has changed substantially since this was created so this repo should be considered deprecated (sorry). I may get around to updating it over the coming new year but likely not before then.

If you are interested in working with LLVM rather than making a clang plugin (or if you are a student presently enrolled in my class), you might be interested my llvm-demo repo instead.

**Comment by nsumner** [comment]
FYI, after updating things for LLVM 11, I looked at this again. It looks to me like your clang development headers were not correctly detected. Make sure that you have not only the LLVM development libraries but also the clang development libraries installed. It will also require clang 11 or greater now.

A stronger FindClang module would produce some better error messages for this.

**Comment by gwangmu** [comment]
I think this is because the version header file in the clang include directory has changed its name from 'Version.h' to 'Version.inc' (tools/clang/include/clang/Basic/Version.inc). Reflecting this at Line 15 of FindClang.cmake worked for me.

**Comment by gwangmu** [comment]
I fixed FindClang.cmake a little to work on LLVM 12. It seems like LLVM 12 does not export static analyzer's header files anymore. I just made it to use the ones in the main source tree.
```
if (NOT LLVM_INCLUDE_DIRS OR NOT LLVM_LIBRARY_DIRS)
   message(FATAL_ERROR "No LLVM and Clang support requires LLVM")
else (NOT LLVM_INCLUDE_DIRS OR NOT LLVM_LIBRARY_DIRS)

function(add_suffix oldlist suffix newlist)
   set(locallist "")
   foreach(element ${${oldlist}})
      list(APPEND locallist "${element}${suffix}")
   endforeach(element)
   set(${newlist} "${locallist}" PARENT_SCOPE)
endfunction(add_suffix)

function(set_clang_include_dirs)
  add_suffix(LLVM_INCLUDE_DIRS "/../../clang/include/" SEARCH_HINTS_STATIC)
  find_path(STATIC_INCLUDES clang/Basic/Version.h
            HINTS ${LLVM_INCLUDE_DIRS} ${SEARCH_HINTS_STATIC})
  add_suffix(LLVM_INCLUDE_DIRS "/../tools/clang/include/" SEARCH_HINTS_DYNAMIC)
  find_path(DYNAMIC_INCLUDES clang/Config/config.h
            HINTS ${LLVM_INCLUDE_DIRS} ${SEARCH_HINTS_DYNAMIC})
  string(COMPARE NOTEQUAL ${STATIC_INCLUDES} ${DYNAMIC_INCLUDES} DIFFERENT)
  if (DIFFERENT)
    list(APPEND STATIC_INCLUDES ${DYNAMIC_INCLUDES})
  endif (DIFFERENT)
  set(CLANG_INCLUDE_DIRS ${STATIC_INCLUDES} PARENT_SCOPE)
endfunction(set_clang_include_dirs)

set_clang_include_dirs()

endif (NOT LLVM_INCLUDE_DIRS OR NOT LLVM_LIBRARY_DIRS)
```
